---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kapp-controller
  namespace: kapp-controller
  labels:
    app: kapp-controller
spec:
  namespaceSelector:
    matchNames:
      - kapp-controller
  selector:
    matchLabels:
      app: kapp-controller
  endpoints:
    - port: metrics
      path: /metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kc-service-monitor-role
  namespace: kapp-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
...

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kc-service-monitor-role-binding
  namespace: kapp-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kc-service-monitor-role
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
...
