#@ load("@ytt:data", "data")
#! --- this won't work ---

#@ for idx in range(0, data.values.count):
---
#@ appidx = idx + 1
#@ appname="sleep-app" + str(appidx)
apiVersion: v1
kind: Secret
metadata:
  name: #@ appname + "-values
  namespace: sleeptest
stringData:
  values2.yml: |
    #@data/values
    ---
    app: 
      name: sleep-app1
